clear all


CORE_envparams_WID_lasso_29Nov_gefs09_base_serial_deepmet

CORE_envparams_WID_lasso_04Dec_gefs19_base_serial_deepmet

CORE_envparams_WID_lasso_22Jan_gefs18_base_serial_deepmet

CORE_envparams_WID_lasso_23Jan_gefs18_base_serial_deepmet

CORE_envparams_WID_lasso_25Jan_eda07_base_serial_deepmet

CORE_envparams_WID_lasso_29Jan_gefs11_base_serial_deepmet

CORE_envparams_WID_lasso_08Feb_eda08_base_serial_deepmet
