function parsaver1(fname, NANdiag, CAPE_mu, LCL_height_mu ,LFC_height_mu, EL_height_mu, ...
                     CIN_NA_fract_mu, CIN_NA_mu, CAPEacbl_IB_mu, initial_ht_parcel_mu, ...
                     CAPE_sfc, LCL_height_sfc, LFC_height_sfc, EL_height_sfc,...
                     CIN_NA_fract_sfc, CIN_NA_sfc, CAPEacbl_IB_sfc, CAPE_ml, LCL_height_ml,...
                     LFC_height_ml, EL_height_ml, CIN_NA_fract_ml, CIN_NA_ml, CAPEacbl_IB_ml, ...
                     RH_mean_ACBL, shear_mag_bulk_ACBL_mu, Ucrel_mu, Vcrel_mu, thetae_mu, thetae_mean_subcloud_mu, ...
                     rvap_mu, thetae_mean_ACBL_mu, shear_mag_bulk_FT_mu, shear_dir_bulk_FT_mu, ...
                     shear_mag_bulk_0to1km, shear_dir_bulk_0to1km, ...
                     shear_mag_bulk_0to3km, shear_dir_bulk_0to3km, shear_mag_bulk_0to6km, shear_dir_bulk_0to6km, ...
                     rvap_850mb, rvap_700mb, rvap_500mb, rh_850mb, rh_700mb, rh_500mb, freezing_ht, PW,...
                     Ucrel_mean_ACBL_mu, Vcrel_mean_ACBL_mu,...
                     shear_mag_bulk_0to9km, shear_dir_bulk_0to9km,...
                     rvap_925mb, rh_925mb, rvap_600mb, rh_600mb,...
                     pCAPE_sfc, pCIN_NA_sfc, pCAPE_ml, pCIN_NA_ml, pCAPE_mu, pCIN_NA_mu, cell_motion_x, cell_motion_y,cellnum);
                
                
                
                
                save(fname, 'NANdiag', 'CAPE_mu', 'LCL_height_mu' , 'LFC_height_mu', 'EL_height_mu', ...
                     'CIN_NA_fract_mu', 'CIN_NA_mu', 'CAPEacbl_IB_mu', 'initial_ht_parcel_mu', ...
                     'CAPE_sfc', 'LCL_height_sfc', 'LFC_height_sfc', 'EL_height_sfc',...
                     'CIN_NA_fract_sfc', 'CIN_NA_sfc', 'CAPEacbl_IB_sfc', 'CAPE_ml', 'LCL_height_ml',...
                     'LFC_height_ml', 'EL_height_ml', 'CIN_NA_fract_ml', 'CIN_NA_ml', 'CAPEacbl_IB_ml', ...
                     'RH_mean_ACBL', 'shear_mag_bulk_ACBL_mu', 'Ucrel_mu', 'Vcrel_mu', 'thetae_mu', 'thetae_mean_subcloud_mu', ...
                     'rvap_mu', 'thetae_mean_ACBL_mu', 'shear_mag_bulk_FT_mu', 'shear_dir_bulk_FT_mu', ...
                     'shear_mag_bulk_0to1km', 'shear_dir_bulk_0to1km', ...
                     'shear_mag_bulk_0to3km', 'shear_dir_bulk_0to3km', 'shear_mag_bulk_0to6km', 'shear_dir_bulk_0to6km', ...
                     'rvap_850mb', 'rvap_700mb', 'rvap_500mb', 'rh_850mb', 'rh_700mb', 'rh_500mb', 'freezing_ht', 'PW',...
                     'Ucrel_mean_ACBL_mu', 'Vcrel_mean_ACBL_mu',  ...
                     'shear_mag_bulk_0to9km', 'shear_dir_bulk_0to9km',...
                     'rvap_925mb', 'rh_925mb', 'rvap_600mb', 'rh_600mb',...
                     'pCAPE_sfc', 'pCIN_NA_sfc', 'pCAPE_ml', 'pCIN_NA_ml', 'pCAPE_mu', 'pCIN_NA_mu', 'cell_motion_x', 'cell_motion_y', 'cellnum');
                
end



