clear all



%CORE_envparams_WID_lasso_29Nov_gefs09_base_serworks_upslope
%CORE_envparams_WID_lasso_04Dec_gefs19_base_serworks_upslope  
%CORE_envparams_WID_lasso_22Jan_gefs18_base_serworks_upslope
%CORE_envparams_WID_lasso_23Jan_gefs18_base_serworks_upslope
%CORE_envparams_WID_lasso_25Jan_eda07_base_serworks_upslope
%CORE_envparams_WID_lasso_29Jan_gefs11_base_serworks_upslope
CORE_envparams_WID_lasso_08Feb_eda08_base_serworks_upslope
